/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * JiaScene.ls
 */
export class StartSceneBase extends Laya.Scene {
    public progress!: Laya.ProgressBar;
}

